import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Inter, Prata } from 'next/font/google'
import './global.css'

import { auth } from '@/auth'

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter'
})

const prata = Prata({
	weight: ['400'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-prata'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await auth()
	return (
		<SessionProvider session={session}>
			<html lang='en'>
				<body
					className={`${inter.variable} ${prata.variable} font-sans antialiased`}
				>
					{children}
				</body>
			</html>
		</SessionProvider>
	)
}
