import type { Metadata } from 'next'
import { Inter, Prata } from 'next/font/google'

import './globals.css'
import ToastProvider from '@/components/providers/ToastProvider'

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter'
})

const prata = Prata({
	weight: ['400'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-prata'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${prata.variable} ${inter.variable} font-sans antialiased min-h-screen`}
			>
				<ToastProvider>{children}</ToastProvider>
			</body>
		</html>
	)
}
