services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: nu_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: mvn spring-boot:run
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nu_portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      UPLOADS_DIR: /app/uploads/profilePicture

volumes:
  pgdata:
  uploads:
